In [1]:
import pandas as pd
import numpy as np

In [2]:
diary=pd.read_csv("C:/Users/yumeng.zou/Google Drive/Freshyear/Summer/Research/1819 diary.csv")

In [3]:
diary.head()

,Date,Time,Type,Subtype,Place,Participants,Participants.1,Participants.2,Participants.3,Participants.4,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,23-12-09,NaN,Education,NaN,麗澤軒,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,23-12-10,NaN,Reading,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,23-12-13,NaN,Education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23-12-18,NaN,Education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,24-01-23,NaN,Education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
diary.index

RangeIndex(start=0, stop=995, step=1)

In [5]:
diary.columns

Index([u'Date', u'Time', u'Type', u'Subtype', u'Place', u'Participants',
       u'Participants.1', u'Participants.2', u'Participants.3',
       u'Participants.4', u'Participants.5', u'Unnamed: 11', u'Unnamed: 12',
       u'Unnamed: 13', u'Unnamed: 14', u'Unnamed: 15', u'Unnamed: 16',
       u'Unnamed: 17', u'Unnamed: 18', u'Unnamed: 19', u'Unnamed: 20',
       u'Unnamed: 21', u'Unnamed: 22', u'Unnamed: 23', u'Unnamed: 24',
       u'Unnamed: 25'],
      dtype='object')

In [6]:
diary.dropna(how='all',inplace=True)
diary.dropna(axis=1,how='all',inplace=True)
diary.tail()

,Date,Time,Type,Subtype,Place,Participants,Participants.1,Participants.2,Participants.3,Participants.4,Participants.5
551,NaN,NaN,Go_places,NaN,月林堂,黎楷屏,NaN,NaN,NaN,NaN,NaN
552,24-09-01,NaN,寫字,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
553,NaN,NaN,Reading,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
554,NaN,NaN,Visited,Yes,NaN,黎楷屏,NaN,NaN,NaN,NaN,NaN
555,NaN,NaN,Visited,Yes,NaN,蔡七婿,NaN,NaN,NaN,NaN,NaN

In [12]:
mid=diary[['Type','Subtype','Participants','Participants.1','Participants.2','Participants.3','Participants.4','Participants.5']]
mid.set_index(['Type','Subtype'],inplace=True)
mid

                         Participants Participants.1 Participants.2  \
Type           Subtype
Education      NaN                NaN            NaN            NaN
Reading        NaN                NaN            NaN            NaN
Education      NaN                NaN            NaN            NaN
               NaN                NaN            NaN            NaN
               NaN                NaN            NaN            NaN
               NaN                NaN            NaN            NaN
               NaN                NaN            NaN            NaN
               NaN                NaN            NaN            NaN
               NaN                NaN            NaN            NaN
               NaN                NaN            NaN            NaN
Marriage       NaN                謝念紹             麥氏            NaN
Education      NaN                 吴錦            NaN            NaN
               NaN                NaN            NaN            NaN
               NaN                NaN            NaN            NaN
               NaN                NaN            NaN            NaN
Meal           NaN                陳仰山            郭三兄            NaN
Letter         NaN                葉夢龍            何夢溪            NaN
Cross_river    NaN                NaN            NaN            NaN
Go_places      NaN                NaN            NaN            NaN
               NaN                NaN            NaN            NaN
               NaN                NaN            NaN            NaN
Education      NaN                NaN            NaN            NaN
Administrative Gazetteer          NaN            NaN            NaN
               Gazetteer          NaN            NaN            NaN
               Gazetteer          NaN            NaN            NaN
Religious      Morning            NaN            NaN            NaN
               NaN                NaN            NaN            NaN
Education      NaN                NaN            NaN            NaN
Go_places      NaN                NaN            NaN            NaN
Letter         Send               黎楷屏            NaN            NaN
...                               ...            ...            ...
Go_places      NaN                NaN            NaN            NaN
Inviting       NaN                鶴暖鄉            李實園            NaN
Visiting       NaN                溫雪子            NaN            NaN
Go_places      NaN                NaN            NaN            NaN
上墳             NaN                NaN            NaN            NaN
Visited        Yes                李實園            NaN            NaN
Recreation     NaN                李實園            NaN            NaN
Meal           NaN                李實園            NaN            NaN
Visiting       NaN                溫雪子            NaN            NaN
Invited        Yes                伍秉鑒            NaN            NaN
Meal           NaN                伍秉鑒            NaN            NaN
Theater        NaN                伍秉鑒            NaN            NaN
Social         NaN                夏修恕            NaN            NaN
               Birthday           伍秉鏞            NaN            NaN
寫字             NaN                NaN            NaN            NaN
Drink          NaN                伍秉鏞            黎楷屏            溫雪子
Go_places      NaN                NaN            NaN            NaN
               NaN                NaN            NaN            NaN
Visiting       Yes                越煉師            NaN            NaN
               Yes               朴石前輩            NaN            NaN
Painting       NaN                NaN            NaN            NaN
Visiting       Yes                陳仰山            NaN            NaN
               Yes                陳仰山            伍秉鑒            NaN
Recreation     NaN                黎楷屏            NaN            NaN
               NaN                黎楷屏            NaN            NaN
Go_places      NaN                黎楷屏            NaN            NaN
寫字             NaN                NaN            NaN            NaN
Reading        NaN                NaN            NaN            NaN
Visited        Yes                黎楷屏            NaN            NaN
               Yes                蔡七婿            NaN            NaN

                         Participants.3 Participants.4 Participants.5
Type           Subtype
Education      NaN                  NaN            NaN            NaN
Reading        NaN                  NaN            NaN            NaN
Education      NaN                  NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
Marriage       NaN                  NaN            NaN            NaN
Education      NaN                  NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
Meal           NaN                  NaN            NaN            NaN
Letter         NaN                  NaN            NaN            NaN
Cross_river    NaN                  NaN            NaN            NaN
Go_places      NaN                  NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
Education      NaN                  NaN            NaN            NaN
Administrative Gazetteer            NaN            NaN            NaN
               Gazetteer            NaN            NaN            NaN
               Gazetteer            NaN            NaN            NaN
Religious      Morning              NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
Education      NaN                  NaN            NaN            NaN
Go_places      NaN                  NaN            NaN            NaN
Letter         Send                 NaN            NaN            NaN
...                                 ...            ...            ...
Go_places      NaN                  NaN            NaN            NaN
Inviting       NaN                  NaN            NaN            NaN
Visiting       NaN                  NaN            NaN            NaN
Go_places      NaN                  NaN            NaN            NaN
上墳             NaN                  NaN            NaN            NaN
Visited        Yes                  NaN            NaN            NaN
Recreation     NaN                  NaN            NaN            NaN
Meal           NaN                  NaN            NaN            NaN
Visiting       NaN                  NaN            NaN            NaN
Invited        Yes                  NaN            NaN            NaN
Meal           NaN                  NaN            NaN            NaN
Theater        NaN                  NaN            NaN            NaN
Social         NaN                  NaN            NaN            NaN
               Birthday             NaN            NaN            NaN
寫字             NaN                  NaN            NaN            NaN
Drink          NaN                  NaN            NaN            NaN
Go_places      NaN                  NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
Visiting       Yes                  NaN            NaN            NaN
               Yes                  NaN            NaN            NaN
Painting       NaN                  NaN            NaN            NaN
Visiting       Yes                  NaN            NaN            NaN
               Yes                  NaN            NaN            NaN
Recreation     NaN                  NaN            NaN            NaN
               NaN                  NaN            NaN            NaN
Go_places      NaN                  NaN            NaN            NaN
寫字             NaN                  NaN            NaN            NaN
Reading        NaN                  NaN            NaN            NaN
Visited        Yes                  NaN            NaN            NaN
               Yes                  NaN            NaN            NaN

[556 rows x 6 columns]